# Generated by hand for the initial public scaffold.
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CanonicalCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_expansion", models.CharField(max_length=64)),
                ("source_catalog_id", models.CharField(max_length=160)),
                ("card_number_raw", models.CharField(max_length=160)),
                ("card_number_normalized", models.CharField(db_index=True, max_length=160)),
                ("name_jp", models.CharField(blank=True, max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255)),
                ("rarity", models.CharField(blank=True, max_length=64)),
                ("set_code", models.CharField(blank=True, max_length=64)),
                ("set_name", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField(blank=True)),
                ("catalog_payload_json", models.JSONField(default=dict)),
                ("catalog_hash", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("last_imported_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("base_domain", models.CharField(max_length=160)),
                ("enabled", models.BooleanField(default=False)),
                ("implemented", models.BooleanField(default=False)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("supports_exact_stock", models.BooleanField(default=False)),
                ("scrape_interval_minutes", models.PositiveIntegerField(default=360)),
                ("schedule_offset_minutes", models.PositiveIntegerField(default=0)),
                ("minimum_request_delay_ms", models.PositiveIntegerField(default=1500)),
                ("shipping_rule_type", models.CharField(choices=[("flat", "Flat"), ("free_threshold", "Free threshold")], default="flat", max_length=32)),
                ("shipping_base_jpy", models.PositiveIntegerField(default=0)),
                ("free_shipping_threshold_jpy", models.PositiveIntegerField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("stale_after_minutes", models.PositiveIntegerField(default=720)),
            ],
            options={"ordering": ["priority", "name"]},
        ),
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("running", "Running"), ("success", "Success"), ("failed", "Failed"), ("skipped", "Skipped")], default="running", max_length=24)),
                ("pages_requested", models.PositiveIntegerField(default=0)),
                ("products_seen", models.PositiveIntegerField(default=0)),
                ("products_updated", models.PositiveIntegerField(default=0)),
                ("products_unmatched", models.PositiveIntegerField(default=0)),
                ("parse_errors", models.PositiveIntegerField(default=0)),
                ("http_errors", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                ("parser_version", models.CharField(blank=True, max_length=80)),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="aggregator.shop")),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="ShopProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("shop_product_key", models.CharField(max_length=200)),
                ("product_url", models.URLField()),
                ("title_raw", models.TextField(blank=True)),
                ("card_code_raw", models.CharField(blank=True, max_length=160)),
                ("card_code_normalized", models.CharField(blank=True, db_index=True, max_length=160)),
                ("condition_raw", models.CharField(blank=True, max_length=160)),
                ("condition_normalized", models.CharField(blank=True, max_length=80)),
                ("match_status", models.CharField(choices=[("unmatched", "Unmatched"), ("auto", "Auto"), ("manual", "Manual"), ("ambiguous", "Ambiguous")], default="unmatched", max_length=24)),
                ("match_confidence", models.FloatField(default=0)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("canonical_card", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="aggregator.canonicalcard")),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="aggregator.shop")),
            ],
        ),
        migrations.CreateModel(
            name="CurrentOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price_jpy", models.PositiveIntegerField()),
                ("stock_quantity", models.IntegerField(blank=True, null=True)),
                ("stock_status", models.CharField(choices=[("available", "Available"), ("sold_out", "Sold out"), ("unknown", "Unknown")], max_length=24)),
                ("stock_kind", models.CharField(choices=[("exact", "Exact"), ("binary", "Binary"), ("unknown", "Unknown")], max_length=24)),
                ("purchase_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("shop_product", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="current_offer", to="aggregator.shopproduct")),
            ],
        ),
        migrations.CreateModel(
            name="OfferHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price_jpy", models.PositiveIntegerField()),
                ("stock_quantity", models.IntegerField(blank=True, null=True)),
                ("stock_status", models.CharField(max_length=24)),
                ("stock_kind", models.CharField(max_length=24)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("scrape_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="aggregator.scraperun")),
                ("shop_product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="aggregator.shopproduct")),
            ],
        ),
        migrations.CreateModel(
            name="CardMatchOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("canonical_card", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="aggregator.canonicalcard")),
                ("shop_product", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="aggregator.shopproduct")),
            ],
        ),
        migrations.AddConstraint(model_name="canonicalcard", constraint=models.UniqueConstraint(fields=("source_expansion", "source_catalog_id"), name="uniq_catalog_source_card")),
        migrations.AddIndex(model_name="canonicalcard", index=models.Index(fields=["card_number_normalized", "rarity"], name="aggregator__card_nu_8bb961_idx")),
        migrations.AddIndex(model_name="canonicalcard", index=models.Index(fields=["set_code", "rarity"], name="aggregator__set_cod_964366_idx")),
        migrations.AddConstraint(model_name="shopproduct", constraint=models.UniqueConstraint(fields=("shop", "shop_product_key"), name="uniq_shop_product")),
        migrations.AddIndex(model_name="shopproduct", index=models.Index(fields=["shop", "active", "match_status"], name="aggregator__shop_id_f0546f_idx")),
        migrations.AddIndex(model_name="currentoffer", index=models.Index(fields=["stock_status", "price_jpy"], name="aggregator__stock_s_281ad1_idx")),
    ]
